codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: false

coverage:
  github_checks:
    annotations: false
  status:
    project:
      default:
        target: 60%
        threshold: 0%
        informational: true
    patch:
      default:
        informational: true

github_checks:
  annotations: false

comment:
  require_changes: false
