coverage:
  github_checks:
    annotations: false
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
    patch:
      default:
        informational: true
