# frozen_string_literal: true

module Astronoby
  class Constants
    DAYS_PER_JULIAN_CENTURY = 36525.0

    HOURS_PER_DAY = 24.0
    DEGREES_PER_CIRCLE = 360.0
    RADIANS_PER_CIRCLE = 2 * Math::PI

    SECONDS_PER_MINUTE = 60.0
    MINUTES_PER_HOUR = 60.0
    MINUTES_PER_DEGREE = 60.0

    SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
    SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY
    SECONDS_PER_DEGREE = SECONDS_PER_MINUTE * MINUTES_PER_DEGREE
    RADIAN_PER_HOUR = Math::PI / 12.0

    PI_IN_DEGREES = 180.0
  end
end
