---
name: Bundler Audit
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Bundler Audit"
        uses: thoughtbot/bundler-audit-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
