name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 3.0.0
          - 3.0.1
          - 3.0.2
          - 3.0.3
          - 3.0.4
          - 3.0.5
          - 3.0.6
          - 3.0.7
          - 3.1.0
          - 3.1.1
          - 3.1.2
          - 3.1.3
          - 3.1.4
          - 3.1.5
          - 3.1.6
          - 3.2.0
          - 3.2.1
          - 3.2.2
          - 3.2.3
          - 3.2.4
          - 3.2.5
          - 3.2.6
          - 3.3.0
          - 3.3.1
          - 3.3.2
          - 3.3.3
          - 3.3.4
          - 3.3.5
          - 3.3.6
          - 3.4.0
          - 3.4.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Check code guidelines
        run: bundle exec standardrb
