name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 3.2.0
          - 3.2.1
          - 3.2.2
          - 3.2.3
          - 3.3.0
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Check code guidelines
        run: bundle exec standardrb
